spring.application.name=SecureLoginPUC

app.user.username=${DEFAULT_USER_USERNAME}
app.user.email=${DEFAULT_USER_EMAIL}
app.user.password=${DEFAULT_USER_PASSWORD}
app.admin.username=${DEFAULT_ADMIN_USERNAME}
app.admin.email=${DEFAULT_ADMIN_EMAIL}
app.admin.password=${DEFAULT_ADMIN_PASSWORD}

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/secureloginpuc
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# API SendEmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
# https://myaccount.google.com/apppasswords
# sua senha de app aqui

spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true  
spring.mail.properties.mail.smtp.starttls.enable=true