spring.application.name=SecureLoginPUC
app.user.username=bernardo
app.user.email=bernardo@email
app.user.password=4321
app.admin.username=admin
app.admin.email=admin@email
app.admin.password=1234

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/secureloginpuc
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console